#+title: Gatsby’s not so great

- tags :: [[file:20200617170955-drafts.org][Drafts]]

* Gatsby’s not so great(for me)

So I have been using Gatsby for almost two years now. I have built a nice looking and fast(I think) blog with 15 odd posts. PWA is out of the box, my component’s are written in react, I can query my post data from graphQL and so many other goodies.

** So why am I moving away you ask?

As with my career decisions I have gradually moved from being a Full-stack(UI Primary) engineer to a back-end/platform engineer. While I still retain my love for React, I believe React shouldn’t be the norm of web development. The whole ecosystem around React is maddening. It’s certainly built for highly interactive web applications, but in my opinion it has no place in a static blog generation.

Also GraphQL is kinda overkill for a blog too.

There are certain pain points that were bugging me for a long time.

1. It’s hard to leverage any library that doesn’t have a React component or Gatsby plugin built for it. e.g [[https://utteranc.es/][Utterances]].
2. Tagging is not so straight-forward. Hugo and Jekyll has a first-class support for it.
3. Running an external script always has been tough and need react specific [[https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml][hacks]].
4. Lack of dedicated and switchable themes.

Creating a blog shouldn’t have to be so complex. A bunch of markdown files and a simple script to convert them into HTML should be enough.

** My new workflow

I have always loved markdown until I discovered [[https://orgmode.org/][Org-mode]]. It simply blew me away. I never thought I could do so much with plain text. And when I learned about [[https://ox-hugo.scripter.co/][ox-hugo]], the idea of publishing a blog completely from emacs fascinated me.

=Org-mode= coupled with =ox-hugo= gave me a significant advantage by managing all my pages in a single org-file. With =ox-hugo= I can convert my articles to hugo supported directory structure and the coolest thing is I can still add posts in markdown which can be independent of my master content file.

Given the fact that this is a programming blog, having the ability to [[https:orgmode.org/worg/org-contrib/babel/][execute source code]] inside the document is really helpful.

** Conclusion

Gatsby has served me good over the past years. Undoubtdly it’s a great software, just not well suited for my needs at the time.
